In [1]:
import matplotlib.pyplot as plt
% matplotlib inline
plt.style.use('ggplot')

In [2]:
import numpy as np
import pandas as pd

In [4]:
articles_df = pd.read_pickle('articles.pkl')

In [5]:
articles_df

document_type                                            web_url  \
0          article  http://www.nytimes.com/2013/10/03/sports/footb...   
1          article  http://www.nytimes.com/2013/10/03/us/new-immig...   
2          article  http://www.nytimes.com/2013/10/03/us/arizona-j...   
3          article  http://www.nytimes.com/2013/10/03/us/texas-sta...   
4          article  http://www.nytimes.com/2013/10/03/sports/tenni...   
5          article  http://www.nytimes.com/2013/10/03/sports/socce...   
6          article  http://www.nytimes.com/2013/10/03/sports/socce...   
7          article  http://www.nytimes.com/2013/10/03/sports/ameri...   
8          article  http://www.nytimes.com/2013/10/03/sports/hocke...   
9          article  http://www.nytimes.com/2013/10/03/sports/vonn-...   
10         article  http://www.nytimes.com/2013/10/03/sports/whitn...   
11         article  http://www.nytimes.com/2013/10/03/us/eight-are...   
12         article  http://www.nytimes.com/2013/10/03/business/ene...   
13         article  http://www.nytimes.com/2013/10/03/world/africa...   
14         article  http://www.nytimes.com/2013/10/03/opinion/prep...   
15         article  http://www.nytimes.com/2013/10/03/opinion/new-...   
16         article  http://www.nytimes.com/2013/10/03/opinion/a-bl...   
17         article  http://www.nytimes.com/2013/10/03/opinion/coll...   
18         article  http://www.nytimes.com/2013/10/03/opinion/kris...   
19         article  http://www.nytimes.com/2013/10/03/opinion/does...   
20         article  http://www.nytimes.com/2013/10/03/world/middle...   
21         article  http://www.nytimes.com/2013/10/03/sports/hocke...   
22         article  http://www.nytimes.com/2013/10/03/world/middle...   
23         article  http://www.nytimes.com/2013/10/03/world/asia/e...   
24         article  http://www.nytimes.com/2013/10/03/world/europe...   
25         article  http://www.nytimes.com/2013/10/03/world/europe...   
26         article  http://www.nytimes.com/2013/10/03/sports/baseb...   
27         article  http://www.nytimes.com/2013/10/03/business/med...   
28         article  http://www.nytimes.com/2013/10/03/world/asia/a...   
29         article  http://www.nytimes.com/2013/10/03/arts/televis...   
...            ...                                                ...   
1375       article  http://www.nytimes.com/2013/10/02/world/middle...   
1376       article  http://www.nytimes.com/2013/10/02/opinion/john...   
1377       article  http://www.nytimes.com/2013/10/02/sports/socce...   
1378       article  http://www.nytimes.com/2013/10/02/sports/footb...   
1379       article  http://www.nytimes.com/2013/10/02/us/health-in...   
1380       article  http://www.nytimes.com/2013/10/02/arts/music/v...   
1381       article  http://www.nytimes.com/2013/10/02/us/politics/...   
1382       article  http://www.nytimes.com/2013/10/02/world/middle...   
1383       article  http://www.nytimes.com/2013/10/02/business/int...   
1384       article  http://www.nytimes.com/2013/10/01/arts/design/...   
1385       article  http://www.nytimes.com/2013/10/01/sports/baseb...   
1386       article  http://www.nytimes.com/2013/10/01/business/ene...   
1387       article  http://www.nytimes.com/2013/10/01/opinion/day-...   
1388       article  http://www.nytimes.com/2013/10/01/world/africa...   
1389       article  http://www.nytimes.com/2013/10/01/business/med...   
1390       article  http://www.nytimes.com/2013/10/01/sports/baseb...   
1391       article  http://www.nytimes.com/2013/10/01/opinion/the-...   
1392       article  http://www.nytimes.com/2013/10/01/opinion/beyo...   
1393       article  http://www.nytimes.com/2013/10/01/sports/baske...   
1394       article  http://www.nytimes.com/2013/10/01/us/high-rank...   
1395       article  http://www.nytimes.com/2013/10/01/us/politics/...   
1396       article  http://www.nytimes.com/2013/10/01/business/med...   
1397       article  http://www.nytimes.com/2013/10/01/world/eur

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

wordnet = WordNetLemmatizer()

def lemmatize(doc):
    return [wordnet.lemmatize(word) for word in word_tokenize(doc.lower())]

vectorizer = TfidfVectorizer(stop_words='english', max_features=2000, tokenizer=lemmatize)
vectors = vectorizer.fit_transform(articles_df.content)
words = vectorizer.get_feature_names()

In [9]:
from sklearn.cluster import KMeans

kmeans = KMeans()

kmeans.fit(vectors)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=8, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [10]:
print('cluster centers:')
print(kmeans.cluster_centers_)

cluster centers:
[[0.00621925 0.00423343 0.00289187 ... 0.10585331 0.08408428 0.04741208]
 [0.01243021 0.0118749  0.00404537 ... 0.15940328 0.08300651 0.04256631]
 [0.00236474 0.00740423 0.00555835 ... 0.06778185 0.05881525 0.03158834]
 ...
 [0.00649497 0.00662736 0.00221048 ... 0.12961765 0.08487626 0.04775669]
 [0.00679381 0.0086287  0.00401023 ... 0.14039023 0.07974822 0.041644  ]
 [0.00395092 0.0008342  0.0025054  ... 0.12454957 0.09076568 0.05800897]]


In [16]:
top_centroids = kmeans.cluster_centers_.argsort()[:,-1:-11:-1]
print('top feature for cluster:')
for num, centroid in enumerate(top_centroids):
    print("%d: %s" % (num, ", ".join(words[i] for i in centroid)))

top feature for cluster:
0: mr., ’, s, said, “, party, court, government, ”, state
1: ’, game, team, s, “, season, said, player, league, coach
2: attack, said, syria, ’, killed, chemical, syrian, “, s, weapon
3: “, ’, s, ”, mr., ms., music, new, art, t
4: ’, s, “, said, company, percent, year, ”, new, sept.
5: republican, ’, health, house, government, care, “, shutdown, mr., s
6: yankee, rivera, ’, game, inning, pettitte, season, s, “, run
7: iran, rouhani, iranian, nuclear, mr., ’, obama, s, israel, united


In [17]:
top_centroids

array([[1167, 1997, 1559, 1563, 1998, 1278,  446,  793, 1999, 1716],
       [1997,  762, 1795, 1559, 1998, 1589, 1563, 1328, 1024,  367],
       [ 175, 1563, 1776, 1997,  989,  336, 1777, 1998, 1559, 1939],
       [1998, 1997, 1559, 1999, 1167, 1169, 1174, 1201,  160, 1778],
       [1997, 1559, 1998, 1563,  390, 1295, 1988, 1999, 1201, 1611],
       [1499, 1997,  828,  863,  793,  298, 1998, 1640, 1167, 1559],
       [1986, 1536, 1997,  762,  909, 1306, 1589, 1559, 1998, 1552],
       [ 933, 1545,  934, 1213, 1167, 1997, 1216, 1559,  940, 1883]])